name: Go

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.24.x'

    - name: Install dependencies (Ripgrep & FZF)
      run: |
        sudo apt-get update
        sudo apt-get install -y ripgrep fzf

    - name : Run fmt
      run: go fmt ./...
      env:
        # Ensure tests run in "Native" mode
        CGO_ENABLED: 0

    - name : Run Vet
      run: go vet ./...
      env:
        # Ensure tests run in "Native" mode
        CGO_ENABLED: 0

    - name: Run Test
      run: go test -v ./...
      env:
        # Ensure tests run in "Native" mode
        CGO_ENABLED: 0

    - name: Run Build
      run: go build -v ./...
      env:
        # Ensure tests run in "Native" mode
        CGO_ENABLED: 0